FROM node:15
RUN mkdir -p server_app
WORKDIR /server_app
COPY ./server/package.json .
ARG NODE_ENV
RUN if [ "$NODE_ENV" = "development" ]; \
        then npm install; \
        else npm install --only=production; \
        fi
COPY /server/ ./
CMD ["node", "index.js"]


