FROM node:15 as dependencies
WORKDIR /client_app
COPY ./client/package.json .
ARG NODE_ENV
RUN if [ "$NODE_ENV" = "development" ]; \
        then npm install; \
        else npm install --only=production; \
        then npm install --global --unsage-perm serve; \
        fi
COPY /client/ ./
# CMD ["npm", "install", "--global", "--unsafe-perm", "serve"]
CMD ["npm", "run", "build"]
CMD ["serve", "-s", "out", "-p", "3000"]


