version: "3"
services:
    nginx: 
        ports:
            - "80:80"
            
    node-app:
        deploy:
            replicas: 4
            restart_policy:
                condition: any
            update_config:
                parallelism: 2
                delay: 15s
        build:
            context: .
            args:
                NODE_ENV: production
        environment:
            - NODE_ENV=production
        command: node index.js
    
    nextjs:
        build:
            context: .
            args:
                NODE_ENV: production
        environment:
            - NODE_ENV=production  
        command: bash -c "serve -s out -p 3000"