FROM node:15
RUN mkdir -p /app/client
WORKDIR /app/client
COPY ./client/package.json .
ARG NODE_ENV
RUN if [ "$NODE_ENV" = "development" ]; \
        then npm install; \
        else npm install --only=production; \
        fi
COPY /client/ ./
ENV PORT 3000
EXPOSE $PORT
CMD ["npm", "start"]


