version: "3"
services:
    nginx: 
        ports:
            - "80:80"
            
    node-app:
        deploy:
            replicas: 2
            restart_policy:
                condition: any
            update_config:
                parallelism: 1
                delay: 15s
        build:
            context: .
            args:
                NODE_ENV: production
        environment:
            - NODE_ENV=production
        command: node index.js
    
    nextjs:
        build:
            context: .
            args:
                NODE_ENV: production
        volumes:
            - ./client:/client_app
            - /client_app/node_modules
        environment:
            - NODE_ENV=production  
        command: serve -s out -p 3000