version: "3"
services:
    node-app:
        build:
            args:
                NODE_ENV: development
        volumes:
            - ./server/:/app/server
            - /app/server/node_modules
        environment:
            - NODE_ENV=development
        command: bash -c "node index.js"

    frontend:
        build:
            args:
                NODE_ENV: development
        volumes:
            - ./client:/app/client
            - /app/client/node_modules
        environment:
            - NODE_ENV=development
        command: bash -c "npm start"
    
