version: "3"
services:
    node-app:
        build:
            args:
                NODE_ENV: development
        volumes:
            - ./server/:/server_app
            - /server_app/node_modules
        environment:
            - NODE_ENV=development
        command: bash -c "node index.js"

    nextjs:
        build:
            context: .
            args:
                NODE_ENV: development
        volumes:
            - ./client:/client_app
            - /client_app/node_modules
        environment:
            - NODE_ENV=development  
        command: bash -c "npm run dev"
    
