FROM node:15
RUN mkdir -p /client_app
WORKDIR /client_app
COPY ./client/package.json .
ARG NODE_ENV
RUN if [ "$NODE_ENV" = "development" ]; \
        then npm install; \
        else npm install --only=production; \
        fi
COPY . ./
CMD ["npm", "run", "build"]
CMD ["npm", "i", "-g", "serve"]
CMD ["serve", "-s", "out", "-p", "3000"]


